name: "Setup Node.js and pnpm"
description: "Setup Node.js, pnpm, and install dependencies with caching"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "24.11.1"
  install-deps:
    description: "Whether to install dependencies"
    required: false
    default: "true"

outputs:
  pnpm-store-path:
    description: "pnpm store path"
    value: ${{ steps.pnpm-store.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Get pnpm store directory
      id: pnpm-store
      shell: bash
      run: echo "path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

    - name: Setup pnpm cache
      uses: actions/cache@v5
      with:
        path: ${{ steps.pnpm-store.outputs.path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
