name: "Detect Changed Apps"
description: "Detect which apps have changed based on git diff or manual input"

inputs:
  manual_scopes:
    description: "Comma-separated list of app names to include (overrides auto-detection)"
    required: false
  changed_files:
    description: "Optional: changed files list (space or newline separated)"
    required: false
  base_ref:
    description: "Base ref for comparison (default: HEAD~1 for push, base ref for PR)"
    required: false
  apps_config:
    description: "Path to apps config file"
    required: false
    default: ".github/app-config/apps.yml"

outputs:
  scopes:
    description: "Comma-separated list of changed app names"
    value: ${{ steps.detect.outputs.scopes }}
  has_changes:
    description: "Whether any apps have changes"
    value: ${{ steps.detect.outputs.has_changes }}

runs:
  using: "composite"
  steps:
    - name: Detect changed apps
      id: detect
      shell: bash
      run: |
        set -e

        echo "=========================================="
        echo "Detect Changed Apps"
        echo "=========================================="

        MANUAL_SCOPES="${{ inputs.manual_scopes }}"
        APPS_CONFIG="${{ inputs.apps_config }}"
        CHANGED_FILES="${{ inputs.changed_files }}"
        BASE_REF="${{ inputs.base_ref }}"

        # Manual scopes override
        if [ -n "$MANUAL_SCOPES" ]; then
          echo "Using manual scopes: $MANUAL_SCOPES"
          echo "scopes=$MANUAL_SCOPES" >> "$GITHUB_OUTPUT"
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Get changed files
        if [ -z "$CHANGED_FILES" ]; then
          if [ -z "$BASE_REF" ]; then
            if [ "${{ github.event_name }}" == "pull_request" ]; then
              BASE_REF="${{ github.event.pull_request.base.sha }}"
            else
              BASE_REF="HEAD~1"
            fi
          fi
          echo "Comparing against: $BASE_REF"
          CHANGED_FILES=$(git diff --name-only "$BASE_REF" HEAD 2>/dev/null || echo "")
        fi

        if [ -z "$CHANGED_FILES" ]; then
          echo "No changed files detected"
          echo "scopes=" >> "$GITHUB_OUTPUT"
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "Changed files:"
        echo "$CHANGED_FILES" | head -20
        if [ $(echo "$CHANGED_FILES" | wc -l) -gt 20 ]; then
          echo "... and more"
        fi
        echo ""

        # Read app names from config (pure bash, no yq dependency)
        APP_NAMES=$(grep -E '^\s+-\s+app:\s+' "$APPS_CONFIG" 2>/dev/null | sed 's/.*app:\s*//' | tr -d ' ' || echo "")
        if [ -z "$APP_NAMES" ]; then
          echo "No apps found in config"
          echo "scopes=" >> "$GITHUB_OUTPUT"
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Check if packages changed (affects all apps)
        PACKAGES_CHANGED=false
        if echo "$CHANGED_FILES" | grep -q "^packages/"; then
          PACKAGES_CHANGED=true
          echo "packages/** changed - will include all apps"
        fi

        # Check if CI-related files changed (affects all apps)
        CI_CHANGED=false
        if echo "$CHANGED_FILES" | grep -qE "^\.github/(workflows|actions|app-config)/"; then
          CI_CHANGED=true
          echo ".github CI files changed - will include all apps"
        fi

        # Detect affected apps
        AFFECTED=""
        for APP in $APP_NAMES; do
          APP_CHANGED=false

          # Check if app directory changed
          if echo "$CHANGED_FILES" | grep -q "^apps/${APP}/"; then
            APP_CHANGED=true
          fi

          # Include if packages/CI changed or app changed
          if [ "$PACKAGES_CHANGED" = true ] || [ "$CI_CHANGED" = true ] || [ "$APP_CHANGED" = true ]; then
            if [ -n "$AFFECTED" ]; then
              AFFECTED="${AFFECTED},${APP}"
            else
              AFFECTED="$APP"
            fi
            echo "  [affected] $APP"
          fi
        done

        echo ""
        echo "Affected apps: ${AFFECTED:-none}"
        echo "=========================================="

        echo "scopes=$AFFECTED" >> "$GITHUB_OUTPUT"
        if [ -n "$AFFECTED" ]; then
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
        else
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
        fi
